services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kb_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  floci:
    image: floci/floci:latest
    container_name: floci-local
    ports:
      - "4566:4566"
    volumes:
      - flocidata:/app/data

volumes:
  pgdata:
  flocidata: