-- 001_init_schema.sql
-- Create base tables for incidents, embeddings, and architecture docs

CREATE TABLE IF NOT EXISTS incidents (
    incident_id SERIAL PRIMARY KEY,
    service VARCHAR(50),
    error_log TEXT,
    root_cause TEXT,
    resolution TEXT,
    validated BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS incident_embeddings;
CREATE TABLE IF NOT EXISTS incident_embeddings (
    incident_id INT REFERENCES incidents(incident_id),
    embedding vector(384)  -- adjust to match your embedding model dimension
);
ALTER TABLE incident_embeddings
ADD CONSTRAINT incident_embeddings_unique UNIQUE (incident_id);

CREATE TABLE IF NOT EXISTS architecture_docs (
    doc_id SERIAL PRIMARY KEY,
    title VARCHAR(150),          -- Document title
    content TEXT,                -- Main textual content
    image_paths TEXT[],          -- Array of image references (supports multiple diagrams)
    doc_type VARCHAR(50),        -- e.g. 'manual', 'flow', 'architecture'
    file_path TEXT,              -- Path to the actual .docx or .pdf file
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE architecture_doc_chunks (
    chunk_id BIGSERIAL PRIMARY KEY,
    doc_id INT REFERENCES architecture_docs(doc_id),
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    embedding vector(384) NOT NULL
);
CREATE TABLE architecture_doc_chunks (
    chunk_id SERIAL PRIMARY KEY,
    doc_id INT NOT NULL,
    chunk_index INT NOT NULL,
    content TEXT NOT NULL,
    embedding VECTOR(768),   -- or 384 depending on model
    metadata JSONB,           -- flexible metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.architecture_docs (
    doc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150),
    content TEXT,
    image_paths TEXT[],
    doc_type VARCHAR(50),
    file_path TEXT,
    image_data BYTEA,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.architecture_doc_chunks (
    chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT NOT NULL REFERENCES public.architecture_docs(doc_id)
        ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    embedding VECTOR(768) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (doc_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS public.analyzer_rcas (
    rca_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_query TEXT NOT NULL,
    incident_ids INTEGER[] NOT NULL DEFAULT '{}',
    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    rca_json JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ALTER TABLE public.analyzer_rcas
--     ADD COLUMN IF NOT EXISTS incident_ids INTEGER[] NOT NULL DEFAULT '{}';

-- ALTER TABLE public.analyzer_rcas
--     ADD COLUMN IF NOT EXISTS evidence JSONB NOT NULL DEFAULT '{}'::jsonb;